#ifndef SCINTILLA_GLOBAL_H
#define SCINTILLA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCINTILLA_LIBRARY)
#  define SCINTILLASHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCINTILLASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCINTILLA_GLOBAL_H
