#ifndef CONSTANT_H
#define CONSTANT_H

enum EWINDOW_STATUS {
    ESTATUS_CREATING,
    ESTATUS_CREATED,
    ESTATUS_DESTORYING,
    ESTATUS_DESTORYED,
    ESTATUS_UNKNOW=-1
};

enum EUSER_DATA {
    EUSERDATA_SCINTILLA_TEXT_EDITOR = 1001,
    EUSERDATA_PATHNAME

};

enum EHOT_KEYS {
    EHT_BOOKMARKS,
    EHT_NEXT_BOOKMARKS
};

#define _NEW_FILE_PREFIX    "NewFile"

#endif // CONSTANT_H
