#ifndef CONSTANT_H
#define CONSTANT_H

enum EWINDOW_STATUS {
    ESTATUS_CREATING,
    ESTATUS_CREATED,
    ESTATUS_DESTORYING,
    ESTATUS_DESTORYED,
    ESTATUS_UNKNOW=-1
};

#define _NEW_FILE_PREFIX    "NewFile"

#endif // CONSTANT_H
